# Generated by Django 5.2.9 on 2025-12-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('pcs', 'шт'), ('kg', 'кг'), ('g', 'г'), ('l', 'л'), ('ml', 'мл')], default='pcs', max_length=10, verbose_name='Одиниця виміру'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name="Вага/Об'єм (число)"),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання'),
        ),
    ]
