# Generated by Django 5.2.9 on 2025-12-04 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_weight_unit_product_weight_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна закупівлі (грн)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Артикул/Код'),
        ),
        migrations.AddField(
            model_name='sale',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Чистий прибуток'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна продажу (грн)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name="Вага/Об'єм"),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата продажу'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Сума продажу'),
        ),
    ]
