# Generated by Django 5.2.9 on 2025-12-04 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_purchase_price_product_sku_sale_profit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Загальна сума')),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Загальний прибуток')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Кількість')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна продажу (за од.)')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна закупівлі')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='Чек')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product', verbose_name='Товар')),
            ],
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
