# Generated by Django 5.2.9 on 2025-12-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_purchase_purchaseitem_supplier_purchase_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='received_applied',
            field=models.BooleanField(default=False, verbose_name='Проведено на склад'),
        ),
    ]
