# Generated by Django 5.2.9 on 2025-12-13 21:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_orderitem_quantity_alter_product_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Позиція чека', 'verbose_name_plural': 'Позиції чека'},
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Термін придатності'),
        ),
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кількість')),
                ('reason', models.CharField(choices=[('damage', 'Бій/Пошкодження'), ('defect', 'Брак'), ('expiry', 'Термін придатності'), ('other', 'Інше')], default='other', max_length=20, verbose_name='Причина списання')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата списання')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Собівартість на момент списання')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writeoffs', to='store.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Списання',
                'verbose_name_plural': 'Списання',
                'ordering': ['-created_at'],
            },
        ),
    ]
