# Generated by Django 5.2.9 on 2025-12-13 22:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_orderitem_options_product_expiry_date_writeoff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writeoff',
            options={'verbose_name': 'Списання', 'verbose_name_plural': 'Списання'},
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('defective', 'Бракований товар'), ('wrong_product', 'Не той товар'), ('changed_mind', 'Передумав покупець'), ('expired', 'Прострочений товар'), ('other', 'Інше')], default='other', max_length=20, verbose_name='Причина повернення')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата повернення')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='store.order', verbose_name='Чек')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Касир')),
            ],
            options={
                'verbose_name': 'Повернення',
                'verbose_name_plural': 'Повернення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кількість')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна продажу за од.')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Собівартість за од.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product', verbose_name='Товар')),
                ('return_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.return', verbose_name='Повернення')),
            ],
            options={
                'verbose_name': 'Позиція повернення',
                'verbose_name_plural': 'Позиції повернення',
            },
        ),
    ]
